kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv002
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pv002/"
  storageClassName: standard
