#javax:
#  net.ssl:
#    key-store: <keystore-path>
#    key-store-password: <keystore-password>
#    trust-store: <truststore-path>
#    trust-store-password: <truststore-password>

mycompany:
  broker:
    producer-url: amqp://localhost:5672
    producer-out-queue: TEST.OUT
    consumer-url: amqp://localhost:5672
    consumer-in-queue: TEST.OUT
    concurrent-consumers: 5
    async-consumer: true
  message:
    #size: 50000
    size: 1000000

    
logging:
  level:
    root: INFO
    com.mycompany.amqp: INFO
    org.apache.qpid: WARN
  pattern:
    file: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{25} - %msg%n"
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{25} - %msg%n"
  path: ./logs
  file:
    max-size: 1024KB
    max-history: 10
    
        
